export {
  handleChat,
  handleDoctor,
  handleRecommend,
  handleHome,
  handleRun,
  handleShow,
  handleBench,
  handleImport,
  handleDaemon,
  handleStop,
  handleUpdate,
  handleBrowse,
  handlePull,
  handleServe,
  handleList,
  handleDeleteModels,
} from "./commands/index";
